### ISSUE TITLE
Images zoom request CORS limitation

### ISSUE THREAD

**Issue by dfsq** [dfsq/wikipediaQuickHints#3]
Recently image zooming stoped working due to CORS limitations.

For example: 

XMLHttpRequest cannot load https://commons.wikimedia.org/wiki/File:Timothy-Leary-Los-Angeles-1989.jpg?uselang=ru. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'chrome-extension://ldnhgfghebflgcndlbppfanbchpgmkna' is therefore not allowed access.

**Comment by crossonrose** [comment]
Okay.
