### ISSUE TITLE
[EXPIRED] Опечатка

### ISSUE THREAD

**Issue by sergeevabc** [dfsq/wikipediaQuickHints#5]
Кажется, в плагин вкралась опечатка — вместо _makrs_ нужно _marks_. Саня, поправим?

![](http://i.imgur.com/EngrbWJ.png)

**Comment by dfsq** [comment]
Да, надо бы поправить, спасибо за то, что обратил внимание, странно, что не замечал этого раньше.

**Comment by sergeevabc** [comment]
Поправили?
